Repository yiisoft/validator, pull requests merged in 2022-09, with the labels that each got.

#305 Fix CI regression
  .github/workflows/build.yml
Labels: type:bug

#310 Sync with translator
  composer.json
  tests/Rule/CompositeHandlerTest.php
  tests/Rule/CountHandlerTest.php
  tests/Rule/HasLengthHandlerTest.php
  tests/Rule/NestedHandlerTest.php
  tests/Stub/TranslatorFactory.php
  tests/ValidatorTest.php
Labels: type:task

#303 Improve variability of `$rules` argument in `Validator::validate()`
  src/Rule/Nested.php
  src/RulesProvider/AttributesRulesProvider.php
  src/Validator.php
  tests/ValidateLogicTest.php
  tests/ValidatorTest.php
Labels: type:enhancement

#312 Improve reflection usage
  src/DataSet/ObjectDataSet.php
  src/RulesProvider/AttributesRulesProvider.php
Labels: status:code review

#315 Update translator version
  composer.json
Labels: type:task

#318 Fix config
  config/common.php
Labels: status:code review

#321 Add method support for `Callback` rule
  README.md
  src/AttributeEventInterface.php
  src/DataSet/ObjectDataSet.php
  src/Rule/Callback.php
  src/Rule/CallbackHandler.php
  tests/DataSet/PHP80/ObjectDataSet80Test.php
  tests/Rule/CallbackHandlerTest.php
  tests/Rule/CallbackTest.php
  tests/Rule/NestedHandlerTest.php
  tests/Stub/ObjectWithCallbackMethod.php
  tests/Stub/ObjectWithNonExistingCallbackMethod.php
  tests/Stub/ObjectWithNonPublicCallbackMethod.php
  tests/Stub/ObjectWithNonStaticCallbackMethod.php
Labels: type:enhancement

#317 Add options' progagation for `Nested` rule
  README.md
  src/BeforeValidationInterface.php
  src/PropagateOptionsInterface.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/Rule/Trait/BeforeValidationTrait.php
  tests/Rule/NestedHandlerTest.php
  tests/Stub/TranslatorFactory.php
Labels: type:enhancement
