Repository yiisoft/validator, pull requests merged in 2022-12, with the labels that each got.

#417 Fix translations
  messages/ru/yii-validator.php
Labels: status:code review

#408 Docs, part 2
  src/Rule/Trait/SkipOnEmptyTrait.php
  src/SkipOnEmptyInterface.php
  tests/Rule/AtLeastTest.php
Labels: type:bug, type:docs

#419 Fix propagate options in `Nested` rule when rules are null
  src/Rule/Nested.php
  tests/Rule/NestedTest.php
Labels: status:code review

#418 Docs, part 4
  README.md
  src/Rule/Trait/WhenTrait.php
  src/WhenInterface.php
Labels: type:task

#421 Docs, part 5
  src/LimitInterface.php
  src/Rule/Count.php
  src/Rule/HasLength.php
  src/Rule/Trait/LimitHandlerTrait.php
  src/Rule/Trait/LimitTrait.php
  tests/Rule/LimitHandlerTraitTest.php
Labels: type:docs

#423 Fix translations
  messages/ru/yii-validator.php
  src/Rule/AtLeast.php
  src/Rule/Nested.php
  tests/Rule/AtLeastTest.php
  tests/Rule/NestedTest.php
Labels: type:task

#425 Fix composite rule handler
  src/Rule/CompositeHandler.php
  src/Rule/Trait/PreValidateTrait.php
  src/Validator.php
  tests/Rule/CompositeTest.php
Labels: status:code review

#426 Validation contex: add raw data and use same context in nested validations
  src/Rule/CompositeHandler.php
  src/Rule/EachHandler.php
  src/Rule/NestedHandler.php
  src/Rule/StopOnErrorHandler.php
  src/ValidationContext.php
  src/Validator.php
  tests/Rule/LimitHandlerTraitTest.php
  tests/ValidationContextTest.php
  tests/ValidatorTest.php
Labels: status:code review

#427 Improve validation context
  README.md
  src/Rule/CompareHandler.php
  src/ValidationContext.php
  src/Validator.php
  tests/Rule/CallbackTest.php
  tests/Rule/LimitHandlerTraitTest.php
  tests/ValidationContextTest.php
  tests/ValidatorTest.php
Labels: status:code review

#424 Docs, part 6
  src/EmptyCriteria/NeverEmpty.php
  src/EmptyCriteria/WhenEmpty.php
  src/EmptyCriteria/WhenNull.php
  src/Exception/InvalidCallbackReturnTypeException.php
  src/Exception/RuleHandlerInterfaceNotImplementedException.php
  src/Exception/RuleHandlerNotFoundException.php
  src/Exception/UnexpectedRuleException.php
  src/SkipOnEmptyInterface.php
  tests/Exception/InvalidCallbackReturnTypeExceptionTest.php
  tests/RuleHandlerContainerTest.php
Labels: type:docs

#429 Fix russian translation
  messages/ru/yii-validator.php
Labels: status:code review

#430 From tests remove validator and translator factories + fix `IsTrue` rule
  src/Rule/IsTrueHandler.php
  tests/Benchmark/MainBench.php
  tests/DataSet/DataSetUsageTest.php
  tests/DataSet/ObjectDataSetTest.php
  tests/Rule/Base/DifferentRuleInHandlerTestTrait.php
  tests/Rule/Base/RuleTestCase.php
  tests/Rule/CallbackTest.php
  tests/Rule/IsTrueTest.php
  tests/Rule/NestedTest.php
  tests/Support/TranslatorFactory.php
  tests/Support/ValidatorFactory.php
  tests/TestEnvironments/Php81/Rule/NestedTest.php
  tests/ValidatorTest.php
Labels: status:code review

#428 Allow callable rules in `Composite` rule + minor refactoring
  src/Helper/RulesNormalizer.php
  src/Rule/Composite.php
  tests/Helper/RulesNormalizerTest.php
  tests/Rule/CompositeTest.php
Labels: status:code review

#435 Docs, part 7
  src/DataSet/ArrayDataSet.php
  src/DataSet/SingleValueDataSet.php
  src/DataSetInterface.php
  src/EmptyCriteria/NeverEmpty.php
  src/EmptyCriteria/WhenEmpty.php
Labels: type:docs

#437 Allow use rule attributes for classes and add support for this in `Nested` rule
  src/Helper/ObjectParser.php
  src/Rule/Nested.php
  tests/Support/Data/NestedClassAttribute.php
  tests/TestEnvironments/Php81/Rule/NestedTest.php
Labels: status:code review

#440 In `Composite` rule call `afterInitAttribute()` in nested rules + add `RulesNormalizerIterator`
  src/Helper/RulesNormalizer.php
  src/Helper/RulesNormalizerIterator.php
  src/Rule/Composite.php
  tests/Support/Data/CompositeWithCallbackAttribute.php
  tests/TestEnvironments/Php81/Rule/CompositeTest.php
Labels: status:code review

#439 Fix message in `UnexpectedRuleException`
  src/Exception/UnexpectedRuleException.php
  tests/Rule/Base/DifferentRuleInHandlerTestTrait.php
Labels: status:code review

#438 In `Nested` rule call `afterInitAttribute()` in nested rules
  src/Rule/Nested.php
  tests/Support/Data/NestedWithCallbackAttribute.php
  tests/TestEnvironments/Php81/Rule/NestedTest.php
Labels: status:code review

#441 Adapt `Composite` rule to inheritance usage
  src/Rule/Composite.php
  tests/Rule/CompositeTest.php
Labels: status:code review

#444 Reinit rules for different objects + Allow use `Count` rule as class attribute
  infection.json.dist
  src/AfterInitAttributeEventInterface.php
  src/Helper/ObjectParser.php
  src/Rule/Callback.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/CountHandler.php
  src/Rule/Nested.php
  tests/DataSet/ObjectDataSetTest.php
  tests/Rule/Base/RuleTestCase.php
  tests/Rule/CallbackTest.php
  tests/Rule/CountTest.php
  tests/Support/Data/CountDto.php
  tests/Support/Rule/RuleWithCallsCount.php
Labels: status:code review

#450 Improve `InvalidCallbackReturnTypeException`
  src/Exception/InvalidCallbackReturnTypeException.php
  tests/Rule/CallbackTest.php
Labels: status:code review

#449 Allow use class name in `ObjectParser` + use `ObjectParser` in `AttributesRulesProvider`
  src/DataSet/ObjectDataSet.php
  src/Helper/ObjectParser.php
  src/RulesProvider/AttributesRulesProvider.php
  tests/Helper/ObjectParserTest.php
  tests/RulesProvider/AttributesRulesProviderTest.php
  tests/Support/Data/SimpleDto.php
Labels: status:code review

#447 Allow pass `iterable<callable|RuleInterface>|callable|RuleInterface` as rules to `Each` rule
  src/Rule/Each.php
  tests/Rule/EachTest.php
Labels: status:code review

#446 Allow use `Each`, `Callback` and `StopOnError` as class attribute
  src/Rule/Callback.php
  src/Rule/CallbackHandler.php
  src/Rule/Count.php
  src/Rule/CountHandler.php
  src/Rule/Each.php
  src/Rule/StopOnError.php
  tests/Rule/CallbackTest.php
  tests/Support/Data/CallbackDto.php
  tests/Support/Data/EachDto.php
  tests/Support/Data/StopOnErrorDto.php
  tests/TestEnvironments/Php81/Rule/EachTest.php
  tests/TestEnvironments/Php81/Rule/StopOnErrorTest.php
Labels: status:code review

#454 Move classes `RulesDumper`, `RuleHandlerContainer` and `SimpleRuleHandlerContainer`
  README.md
  config/common.php
  src/Exception/RuleHandlerInterfaceNotImplementedException.php
  src/Exception/RuleHandlerNotFoundException.php
  src/Helper/RulesDumper.php
  src/Rule/Composite.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/Rule/StopOnError.php
  src/RuleHandlerResolver/RuleHandlerContainer.php
  src/RuleHandlerResolver/SimpleRuleHandlerContainer.php
  src/RuleInterface.php
  src/Validator.php
  tests/ConfigTest.php
  tests/Helper/RulesDumperTest.php
  tests/RuleHandlerResolver/RuleHandlerContainerTest.php
Labels: status:code review

#456 Fix `http://` links
  .github/CODE_OF_CONDUCT.md
  src/Rule/Email.php
  src/Rule/EmailHandler.php
  tests/Rule/JsonTest.php
Labels: status:code review

#445 Docs, part 8
  src/AttributeTranslator/ArrayAttributeTranslator.php
  src/AttributeTranslator/NullAttributeTranslator.php
  src/AttributeTranslator/TranslatorAttributeTranslator.php
  src/AttributeTranslatorInterface.php
  src/AttributeTranslatorProviderInterface.php
  src/DataSet/ArrayDataSet.php
  src/DataSet/ObjectDataSet.php
  src/DataSet/SingleValueDataSet.php
  src/Helper/ObjectParser.php
  tests/Support/Data/Charts/Point.php
  tests/TestEnvironments/Php81/DataSet/ObjectDataSetTest.php
  tests/TestEnvironments/Support/Data/Charts/Chart.php
  tests/TestEnvironments/Support/Data/Charts/Coordinate.php
  tests/TestEnvironments/Support/Data/Charts/Point.php
Labels: type:docs, type:task

#458 Revert "Revert "Docs, part 8""
  src/AttributeTranslator/ArrayAttributeTranslator.php
  src/AttributeTranslator/NullAttributeTranslator.php
  src/AttributeTranslator/TranslatorAttributeTranslator.php
  src/AttributeTranslatorInterface.php
  src/AttributeTranslatorProviderInterface.php
  src/DataSet/ArrayDataSet.php
  src/DataSet/ObjectDataSet.php
  src/DataSet/SingleValueDataSet.php
  src/Helper/ObjectParser.php
  tests/Support/Data/Charts/Point.php
  tests/TestEnvironments/Php81/DataSet/ObjectDataSetTest.php
  tests/TestEnvironments/Support/Data/Charts/Chart.php
  tests/TestEnvironments/Support/Data/Charts/Coordinate.php
  tests/TestEnvironments/Support/Data/Charts/Point.php
Labels: type:docs, type:task

#459 Cleanup and minor improve non-code files
  .editorconfig
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .gitignore
  .styleci.yml
  CHANGELOG.md
  README.md
  composer.json
  phpunit-without-intl.xml
  phpunit.xml.dist
  psalm.xml
Labels: status:code review

#460 Docs, part 9
  src/AfterInitAttributeEventInterface.php
  src/DataSet/ObjectDataSet.php
  src/Helper/DataSetNormalizer.php
  src/Helper/SkipOnEmptyNormalizer.php
  src/PostValidationHookInterface.php
  src/RulesProvider/AttributesRulesProvider.php
Labels: type:docs

#463 Docs, part 10
  src/Error.php
  tests/Support/Data/NestedClassAttribute.php
Labels: type:docs

#468 In `RuleInterface` replace `getHandlerClassName(): string` to `getHandler(): string|RuleHandlerInterface`
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Callback.php
  src/Rule/Compare.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/HasLength.php
  src/Rule/In.php
  src/Rule/Ip.php
  src/Rule/IsTrue.php
  src/Rule/Json.php
  src/Rule/Nested.php
  src/Rule/Number.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/StopOnError.php
  src/Rule/Subset.php
  src/Rule/Url.php
  src/RuleInterface.php
  src/Validator.php
  tests/Rule/NestedTest.php
  tests/Rule/RequiredTest.php
  tests/Rule/RuleWithBuiltInHandler.php
  tests/Support/Rule/NotNullRule/NotNull.php
  tests/Support/Rule/RuleWithCustomHandler.php
  tests/Support/Rule/RuleWithoutOptions.php
  tests/Support/Rule/StubRule/StubRuleWithOptions.php
  tests/ValidatorTest.php
Labels: status:code review

#469 Run unit tests, static tests and composer require checker with PHP 8.2
  .github/workflows/build.yml
  .github/workflows/composer-require-checker.yml
  .github/workflows/static.yml
Labels: status:code review

#462 Allow set default empty criteria for `Required` rule
  src/Rule/Required.php
  src/Rule/RequiredHandler.php
  tests/Rule/RequiredTest.php
Labels: status:code review

#470 Add exception code and previous exception to package exceptions
  src/Exception/InvalidCallbackReturnTypeException.php
  src/Exception/RuleHandlerInterfaceNotImplementedException.php
  src/Exception/RuleHandlerNotFoundException.php
  src/Exception/UnexpectedRuleException.php
  src/RuleHandlerResolver/RuleHandlerContainer.php
  tests/Exception/UnexpectedRuleExceptionTest.php
Labels: status:code review

#465 Docs, part 11
  README.md
  src/Exception/UnexpectedRuleException.php
  src/Helper/PropagateOptionsHelper.php
  src/PropagateOptionsInterface.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/RuleHandlerInterface.php
  src/RuleHandlerResolver/RuleHandlerContainer.php
  src/RuleHandlerResolver/SimpleRuleHandlerContainer.php
  src/RuleHandlerResolverInterface.php
  src/RuleInterface.php
Labels: type:docs

#478 Capitalize "throws" descriptions in PHPDoc
  src/Helper/ObjectParser.php
  src/Helper/SkipOnEmptyNormalizer.php
  src/RuleHandlerResolver/RuleHandlerContainer.php
  src/RuleHandlerResolver/SimpleRuleHandlerContainer.php
  src/RuleHandlerResolverInterface.php
Labels: type:docs

#481 Fixes in `ValidationContext`
  src/ValidationContext.php
  tests/ValidationContextTest.php
Labels: type:task

#483 Docs, part 12
  src/ValidatorInterface.php
Labels: type:docs

#486 Rename parameter "Previous rules errored"
  src/Validator.php
Labels: status:code review

#488 Fix psalm errors
  src/DataSet/ObjectDataSet.php
  src/Helper/ObjectParser.php
  src/Rule/Nested.php
  src/RulesProvider/AttributesRulesProvider.php
Labels: status:code review

#485 Docs, part 13
  src/Rule/Boolean.php
  src/Rule/BooleanHandler.php
  src/Rule/Ip.php
  src/Rule/IsTrue.php
  src/Rule/IsTrueHandler.php
  src/Validator.php
  src/ValidatorInterface.php
  tests/Helper/RulesDumperTest.php
  tests/Rule/BooleanTest.php
  tests/Rule/IsTrueTest.php
Labels: type:bug, type:enhancement, type:docs, type:task

#493 Docs, part 14
  messages/ru/yii-validator.php
  src/EmptyCriteria/NeverEmpty.php
  src/EmptyCriteria/WhenEmpty.php
  src/EmptyCriteria/WhenNull.php
  src/Rule/BooleanValue.php
  src/Rule/In.php
  src/Rule/Json.php
  src/Rule/JsonHandler.php
  src/Rule/Required.php
  src/Rule/RequiredHandler.php
  src/Rule/Subset.php
  src/Rule/SubsetHandler.php
  tests/ConfigTest.php
  tests/Rule/InTest.php
  tests/Rule/NestedTest.php
  tests/Rule/SubsetTest.php
  tests/ValidatorTest.php
Labels: type:bug, type:docs, type:task, type:test

#496 Docs, part 15
  src/Rule/Composite.php
  src/Rule/CompositeHandler.php
  src/Rule/Each.php
  src/Rule/EachHandler.php
  src/Rule/StopOnError.php
  src/Rule/StopOnErrorHandler.php
  tests/Rule/CompositeTest.php
Labels: type:docs
