Repository yiisoft/validator, pull requests merged in 2022-10, with the labels that each got.

#324 Cleanup and minor refactoring
  src/Validator.php
  tests/DataSet/PHP80/ObjectDataSet80Test.php
  tests/Stub/ObjectWithCallbackMethod/ObjectWithCallbackMethod.php
  tests/Stub/ObjectWithCallbackMethod/ObjectWithNonExistingCallbackMethod.php
  tests/Stub/ObjectWithCallbackMethod/ObjectWithNonPublicCallbackMethod.php
  tests/Stub/ObjectWithCallbackMethod/ObjectWithNonStaticCallbackMethod.php
  tests/Stub/PiHandler.php
  tests/Stub/RuleHandler.php
Labels: type:task

#322 Differentiate when value is not passed / `null` is passed
  README.md
  src/DataSet/ArrayDataSet.php
  src/DataSet/MixedDataSet.php
  src/DataSet/ObjectDataSet.php
  src/DataSetInterface.php
  src/PostValidationHookInterface.php
  src/Rule/AtLeastHandler.php
  src/Rule/Required.php
  src/Rule/RequiredHandler.php
  src/Rule/Trait/EmptyCheckTrait.php
  src/Rule/Trait/PreValidateTrait.php
  src/SkipOnEmptyCallback/SkipNone.php
  src/SkipOnEmptyCallback/SkipOnEmpty.php
  src/SkipOnEmptyCallback/SkipOnNull.php
  src/ValidationContext.php
  src/Validator.php
  tests/DataSet/ObjectDataSetTest.php
  tests/Rule/NestedTest.php
  tests/Rule/RequiredTest.php
  tests/Stub/DataSet.php
  tests/Stub/ObjectWithDataSet.php
  tests/Stub/ObjectWithDataSetAndRulesProvider.php
  tests/Stub/RulesProvidedDataSet.php
  tests/ValidateLogicTest.php
  tests/ValidatorTest.php
Labels: type:enhancement

#331 Split `BeforeValidationInterface` to separate interfaces
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Callback.php
  src/Rule/Compare.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/HasLength.php
  src/Rule/InRange.php
  src/Rule/Ip.php
  src/Rule/IsTrue.php
  src/Rule/Json.php
  src/Rule/Nested.php
  src/Rule/Number.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/StopOnError.php
  src/Rule/Subset.php
  src/Rule/Trait/PreValidateTrait.php
  src/Rule/Trait/SkipOnErrorTrait.php
  src/Rule/Trait/WhenTrait.php
  src/Rule/Url.php
  src/SkipOnErrorInterface.php
  src/Validator.php
  src/WhenInterface.php
  tests/Rule/AbstractRuleTest.php
  tests/ValidatorTest.php
Labels: status:code review

#333 Remove `RuleNameTrait`
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Callback.php
  src/Rule/Compare.php
  src/Rule/CompareTo.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/Equal.php
  src/Rule/GreaterThan.php
  src/Rule/GreaterThanOrEqual.php
  src/Rule/HasLength.php
  src/Rule/InRange.php
  src/Rule/Ip.php
  src/Rule/IsTrue.php
  src/Rule/Json.php
  src/Rule/LessThan.php
  src/Rule/LessThanOrEqual.php
  src/Rule/Nested.php
  src/Rule/NotEqual.php
  src/Rule/Number.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/StopOnError.php
  src/Rule/Subset.php
  src/Rule/Trait/RuleNameTrait.php
  src/Rule/Url.php
  tests/Rule/AbstractRuleTest.php
  tests/Rule/AtLeastTest.php
  tests/Rule/BooleanTest.php
  tests/Rule/CallbackTest.php
  tests/Rule/CompareToTest.php
  tests/Rule/CompositeTest.php
  tests/Rule/CountTest.php
  tests/Rule/EachTest.php
  tests/Rule/EmailTest.php
  tests/Rule/EqualTest.php
  tests/Rule/GreaterThanOrEqualTest.php
  tests/Rule/GreaterThanTest.php
  tests/Rule/HasLengthTest.php
  tests/Rule/InRangeTest.php
  tests/Rule/IpTest.php
  tests/Rule/IsTrueTest.php
  tests/Rule/JsonTest.php
  tests/Rule/LessThanOrEqualTest.php
  tests/Rule/LessThanTest.php
  tests/Rule/NestedTest.php
  tests/Rule/NotEqualTest.php
  tests/Rule/NumberTest.php
  tests/Rule/RegexTest.php
  tests/Rule/RequiredTest.php
  tests/Rule/StopOnErrorTest.php
  tests/Rule/SubsetTest.php
  tests/Rule/UrlTest.php
Labels: status:code review

#334 Allow use `AtLeast` rule for arrays + tests refactoring
  src/Rule/AtLeastHandler.php
  tests/Rule/AtLeastHandlerTest.php
  tests/Rule/AtLeastTest.php
Labels: status:code review

#338 Move translator from rule handlers to `Validator` + keep message parameters in `Error`
  README.md
  src/Error.php
  src/Result.php
  src/Rule/AtLeastHandler.php
  src/Rule/BooleanHandler.php
  src/Rule/CallbackHandler.php
  src/Rule/CompareHandler.php
  src/Rule/CountHandler.php
  src/Rule/Each.php
  src/Rule/EachHandler.php
  src/Rule/EmailHandler.php
  src/Rule/HasLengthHandler.php
  src/Rule/InRangeHandler.php
  src/Rule/IpHandler.php
  src/Rule/IsTrueHandler.php
  src/Rule/JsonHandler.php
  src/Rule/NestedHandler.php
  src/Rule/NumberHandler.php
  src/Rule/RegexHandler.php
  src/Rule/RequiredHandler.php
  src/Rule/StopOnErrorHandler.php
  src/Rule/SubsetHandler.php
  src/Rule/Trait/LimitHandlerTrait.php
  src/Rule/UrlHandler.php
  src/SimpleRuleHandlerContainer.php
  src/Validator.php
  tests/Php81/DataSet/ObjectDataSetTest.php
  tests/ResultTest.php
  tests/Rule/EachTest.php
  tests/Rule/NestedTest.php
  tests/Support/Data/Charts/Point.php
  tests/Support/ValidatorFactory.php
  tests/ValidatorTest.php
Labels: status:code review

#340 Fix typo in `Callback`
  src/Rule/Callback.php
  tests/DataSet/ObjectDataSetTest.php
Labels: status:code review

#343 Improve callable rule
  src/Rule/Callback.php
  tests/DataSet/ObjectDataSetTest.php
  tests/Rule/Base/RuleTestCase.php
  tests/Rule/CallbackTest.php
  tests/Support/Data/ObjectWithCallbackMethod/ObjectWithNonPublicCallbackMethod.php
  tests/Support/Data/ObjectWithCallbackMethod/ObjectWithNonStaticCallbackMethod.php
Labels: type:enhancement, status:code review

#346 Fix ComposerRequireChecker error
  composer-require-checker.json
  src/Rule/EmailHandler.php
  src/Rule/UrlHandler.php
Labels: type:bug

#349 Add language attribute
  src/Rule/Email.php
  src/Rule/Regex.php
Labels: status:code review

#350 ComposerRequireChecker config: use extensions instead of whitelist
  .github/workflows/composer-require-checker.yml
  composer-require-checker.json
Labels: type:task

#323 Add caching to ObjectDataSet
  src/DataSet/ObjectDataSet.php
  src/DataSetInterface.php
  tests/Benchmark/ObjectDataSetBench.php
  tests/DataSet/ObjectDataSetTest.php
  tests/Support/Data/ObjectWithCallsCount.php
  tests/Support/Data/ObjectWithDynamicDataSet.php
  tests/ValidatorTest.php
Labels: type:enhancement

#342 `Required` rule: remove `SkipOnEmptyInterface` and add `emptyCallback` option
  README.md
  src/Rule/Required.php
  src/Rule/RequiredHandler.php
  tests/DataSet/ObjectDataSetTest.php
  tests/Php81/DataSet/ObjectDataSetTest.php
  tests/Rule/RequiredTest.php
  tests/ValidatorTest.php
Labels: type:bug

#348 Improve trimming in `Required` rule and handler
  README.md
  src/Rule/Required.php
  src/Rule/RequiredHandler.php
  tests/Rule/RequiredTest.php
Labels: type:task

#352 [Mutants] [Escaped]
  src/Rule/CallbackHandler.php
  src/Rule/Compare.php
  src/Rule/CompareHandler.php
  src/Rule/CompareTo.php
  src/Rule/EachHandler.php
  src/Rule/EmailHandler.php
  src/Rule/NestedHandler.php
  src/Rule/NumberHandler.php
  src/Rule/Trait/LimitTrait.php
  tests/Rule/AtLeastTest.php
  tests/Rule/Base/LimitTestTrait.php
  tests/Rule/Base/SkipOnErrorTestTrait.php
  tests/Rule/Base/WhenTestTrait.php
  tests/Rule/BooleanTest.php
  tests/Rule/CallbackTest.php
  tests/Rule/CompareToTest.php
  tests/Rule/CompositeTest.php
  tests/Rule/CountTest.php
  tests/Rule/EachTest.php
  tests/Rule/EmailTest.php
  tests/Rule/EqualTest.php
  tests/Rule/GreaterThanOrEqualTest.php
  tests/Rule/GreaterThanTest.php
  tests/Rule/HasLengthTest.php
  tests/Rule/InRangeTest.php
  tests/Rule/IpTest.php
  tests/Rule/IsTrueTest.php
  tests/Rule/JsonTest.php
  tests/Rule/LessThanOrEqualTest.php
  tests/Rule/LessThanTest.php
  tests/Rule/NestedTest.php
  tests/Rule/NotEqualTest.php
  tests/Rule/NumberTest.php
  tests/Rule/RegexTest.php
  tests/Rule/RequiredTest.php
  tests/Rule/StopOnErrorTest.php
  tests/Rule/SubsetTest.php
  tests/Rule/UrlTest.php
Labels: type:task
