Repository yiisoft/validator, pull requests merged in 2022-02, with the labels that each got.

#151 Validate nested data, add error details
  README.md
  src/Error.php
  src/Result.php
  src/ResultSet.php
  src/Rule/Callback.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/Rules.php
  tests/ResultSetTest.php
  tests/ResultTest.php
  tests/Rule/CallbackTest.php
  tests/Rule/NestedTest.php
  tests/RulesTest.php
Labels: type:enhancement

#160 Improve handling of incorrect input in MatchRegularExpression rule
  src/Rule/Each.php
  src/Rule/MatchRegularExpression.php
  tests/Rule/MatchRegularExpressionTest.php
Labels: type:bug

#164 Rename Rules to RuleSet
  README.md
  src/Rule.php
  src/Rule/Each.php
  src/Rule/GroupRule.php
  src/Rule/Nested.php
  src/RuleSet.php
  src/RulesDumper.php
  src/Validator.php
  tests/Rule/EachTest.php
  tests/Rule/NestedTest.php
  tests/RulesTest.php
  tests/Stub/CustomUrlRule.php
Labels: type:task

#163 Remove ResultSet
  src/PostValidationHookInterface.php
  src/Result.php
  src/ResultSet.php
  src/Validator.php
  src/ValidatorInterface.php
  tests/AbstractDataSetTest.php
  tests/DataSetTest.php
  tests/ResultSetTest.php
  tests/ResultTest.php
  tests/Rule/NestedTest.php
  tests/RulesDumperTest.php
  tests/RulesProvidedDataSetTest.php
  tests/ValidatorTest.php
Labels: type:task

#166 Add getErrorsIndexedByAttribute() and getCommonErrors() methods to Result class
  src/Result.php
  tests/ResultTest.php
Labels: type:feature

#168 Renaming refactoring objects / messages
  README.md
  src/Result.php
  src/Rule/Callback.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/RuleSet.php
  src/Validator.php
  tests/ResultTest.php
  tests/Rule/AtLeastTest.php
  tests/Rule/CallbackTest.php
  tests/Rule/EachTest.php
  tests/Rule/GroupRuleTest.php
  tests/Rule/HasLengthTest.php
  tests/Rule/JsonTest.php
  tests/Rule/MatchRegularExpressionTest.php
  tests/Rule/NestedTest.php
  tests/Rule/NumberTest.php
  tests/RuleSetTest.php
Labels: type:task

#171 RuleSet::asArray() return all rules
  src/RuleSet.php
  tests/RuleSetTest.php
Labels: status:code review

#178 Update usages and docs after changing default of skipOnError from true to false
  README.md
  tests/Rule/BooleanTest.php
  tests/Rule/NestedTest.php
  tests/RuleSetTest.php
Labels: type:docs, type:task

#177 Remove hasAttribute() from data set
  src/DataSet/ArrayDataSet.php
  src/DataSet/ScalarDataSet.php
  src/DataSetInterface.php
  tests/Rule/NumberTest.php
  tests/Stub/DataSet.php
  tests/Stub/RulesProvidedDataSet.php
Labels: type:task
