Repository yiisoft/validator, pull requests merged in 2022-04, with the labels that each got.

#201 Minor changes
  composer.json
  src/Rule.php
  src/RulesDumper.php
  src/ValidationContext.php
  src/Validator.php
  src/ValidatorInterface.php
Labels: status:code review

#203 Test and document usage of traits with AttributeDataSet
  README.md
  tests/Data/Post.php
  tests/Data/TitleTrait.php
  tests/DataSet/AttributeDataSetTest.php
Labels: type:docs, type:task

#199 Enhance tests
  src/Rule/Ip.php
  tests/DataSet/AbstractDataSetTest.php
  tests/Rule/AtLeastTest.php
  tests/Rule/BooleanTest.php
  tests/Rule/CallbackTest.php
  tests/Rule/CompareToTest.php
  tests/Rule/EachTest.php
  tests/Rule/EmailTest.php
  tests/Rule/GroupRuleTest.php
  tests/Rule/HasLengthTest.php
  tests/Rule/InRangeTest.php
  tests/Rule/IpTest.php
  tests/Rule/JsonTest.php
  tests/Rule/NestedTest.php
  tests/Rule/NumberTest.php
  tests/Rule/RegexTest.php
  tests/Rule/RequiredTest.php
  tests/Rule/SubsetTest.php
  tests/Rule/UrlTest.php
  tests/RuleSetTest.php
  tests/RulesDumperTest.php
  tests/ValidationContextTest.php
  tests/ValidatorTest.php
Labels: status:code review, type:task

#210 Add test for Nested rule - combine dot notation and nested structure case
  tests/Rule/NestedTest.php
Labels: type:task

#208 Chain Result::addError()
  src/Result.php
  tests/ResultTest.php
  tests/RuleSetTest.php
Labels: status:code review, type:task

#204 Add Count rule
  README.md
  src/Rule/Count.php
  tests/Rule/CountTest.php
  tests/Rule/NestedTest.php
Labels: type:enhancement

#207 Combine flat and each rules in attributes
  README.md
  src/DataSet/AttributeDataSet.php
  tests/Data/Charts/Point.php
  tests/DataSet/AttributeDataSetTest.php
Labels: type:enhancement, status:code review

#211 Passing instances in attributes and using composition in rules
  README.md
  tests/Rule/CustomRuleTest.php
Labels: type:docs

#215 Fix incomplete rule options
  src/Rule/AtLeast.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/Ip.php
  src/Rule/Number.php
  src/Rule/Subset.php
  tests/Rule/AtLeastTest.php
  tests/Rule/EachTest.php
  tests/Rule/EmailTest.php
  tests/Rule/IpTest.php
  tests/Rule/NumberTest.php
  tests/RuleSetTest.php
  tests/RulesDumperTest.php
Labels: type:bug
