Repository yiisoft/validator, pull requests merged in 2022-07, with the labels that each got.

#245 Add exceptions to phpdoc
  src/RuleHandlerResolverInterface.php
Labels: status:code review

#246 Add ability to compare an attribute value with another
  src/Rule/CompareTo.php
  src/Rule/CompareToHandler.php
  tests/Rule/AbstractRuleValidatorTest.php
  tests/Rule/CompareToHandlerTest.php
  tests/Rule/CompareToTest.php
Labels: status:code review

#250 Fix instance check in README
  README.md
Labels: type:docs

#256 Fix #242: Document that rule handler should not be called directly
  README.md
  src/Rule/RuleHandlerInterface.php
  tests/Rule/AbstractRuleValidatorTest.php
  tests/Rule/AtLeastHandlerTest.php
  tests/Rule/BooleanHandlerTest.php
  tests/Rule/CallbackHandlerTest.php
  tests/Rule/CompareToHandlerTest.php
  tests/Rule/CompositeHandlerTest.php
  tests/Rule/CountHandlerTest.php
  tests/Rule/EachHandlerTest.php
  tests/Rule/EmailHandlerTest.php
  tests/Rule/GroupRuleHandlerTest.php
  tests/Rule/HasLengthHandlerTest.php
  tests/Rule/InRangeHandlerTest.php
  tests/Rule/IpHandlerTest.php
  tests/Rule/JsonHandlerTest.php
  tests/Rule/NestedHandlerTest.php
  tests/Rule/NumberHandlerTest.php
  tests/Rule/RegexHandlerTest.php
  tests/Rule/RequiredHandlerTest.php
  tests/Rule/SubsetHandlerTest.php
  tests/Rule/UrlHandlerTest.php
Labels: status:code review

#254 Fix #252: Do not extend RulesProviderInterface from DataSetInterface
  src/DataSet/AttributeDataSet.php
  src/RulesProviderInterface.php
  tests/Stub/RulesProvidedDataSet.php
Labels: status:code review

#249 Fix attributes collecting
  README.md
  phpunit.xml.dist
  src/Attribute/Embedded.php
  src/Attribute/HasMany.php
  src/Attribute/HasOne.php
  src/DataSet/AttributeDataSet.php
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/GroupRule.php
  src/Rule/HasLength.php
  src/Rule/InRange.php
  src/Rule/Ip.php
  src/Rule/Json.php
  src/Rule/Nested.php
  src/Rule/Number.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/Subset.php
  src/Rule/Url.php
  tests/Data/Charts/Chart.php
  tests/Data/Charts/ChartsData.php
  tests/Data/Charts/Coordinate.php
  tests/Data/Charts/CustomFormatter.php
  tests/Data/Charts/Point.php
  tests/DataSet/AttributeDataSetTest.php
  tests/DataSet/PHP80/AttributeDataSet80Test.php
  tests/DataSet/PHP81/AttributeDataSet81Test.php
  tests/Stub/CustomUrlRule.php
  tests/Stub/NotRuleAttribute.php
Labels: status:code review

#263 Make context mandatory
  src/Rule/AtLeastHandler.php
  src/Rule/BooleanHandler.php
  src/Rule/CallbackHandler.php
  src/Rule/CompareHandler.php
  src/Rule/CompositeHandler.php
  src/Rule/CountHandler.php
  src/Rule/EachHandler.php
  src/Rule/EmailHandler.php
  src/Rule/GroupRuleHandler.php
  src/Rule/HasLengthHandler.php
  src/Rule/InRangeHandler.php
  src/Rule/IpHandler.php
  src/Rule/JsonHandler.php
  src/Rule/NestedHandler.php
  src/Rule/NumberHandler.php
  src/Rule/RegexHandler.php
  src/Rule/RequiredHandler.php
  src/Rule/SubsetHandler.php
  src/Rule/UrlHandler.php
  src/RuleHandlerInterface.php
Labels: status:code review

#255 Fix #251: Prefer rules to attributes
  src/Validator.php
  tests/DataSet/RulesProvidedDataSetTest.php
Labels: status:code review

#267 Fix #264: Remove GroupRule in favor of Composite
  README.md
  src/Attribute/Embedded.php
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Callback.php
  src/Rule/Compare.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/Equal.php
  src/Rule/GreaterThan.php
  src/Rule/GreaterThanOrEqual.php
  src/Rule/GroupRule.php
  src/Rule/GroupRuleHandler.php
  src/Rule/HasLength.php
  src/Rule/InRange.php
  src/Rule/Ip.php
  src/Rule/Json.php
  src/Rule/LessThan.php
  src/Rule/LessThanOrEqual.php
  src/Rule/Nested.php
  src/Rule/NotEqual.php
  src/Rule/Number.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/Subset.php
  src/Rule/Trait/HandlerClassNameTrait.php
  src/Rule/Url.php
  src/RulesDumper.php
  tests/DataSet/PHP81/AttributeDataSet81Test.php
  tests/Rule/GroupRuleHandlerTest.php
  tests/Rule/GroupRuleTest.php
  tests/Stub/CustomUrlRule.php
  tests/Stub/Rule.php
Labels: status:code review

#268 phpDoc: Specifies the correct type of rules.
  src/Rule/Composite.php
  src/Rule/Each.php
  src/Rule/EachHandler.php
  src/Rule/Nested.php
  src/Validator.php
  src/ValidatorInterface.php
Labels: status:code review

#269 Fix #266: Make behavior expected when passing empty rules explicitly
  src/Validator.php
  src/ValidatorInterface.php
  tests/DataSet/RulesProvidedDataSetTest.php
Labels: status:code review

#275 Add missing options
  src/Rule/Composite.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/Rule/NestedHandler.php
  tests/DataSet/PHP81/AttributeDataSet81Test.php
  tests/Rule/CompositeTest.php
  tests/Rule/EachTest.php
  tests/Rule/NestedHandlerTest.php
  tests/Rule/NestedTest.php
Labels: type:bug

#274 Add "exactly" functionality to HasLength rule and handler
  src/Rule/Count.php
  src/Rule/CountHandler.php
  src/Rule/HasLength.php
  src/Rule/HasLengthHandler.php
  src/Rule/Trait/LimitHandlerTrait.php
  src/Rule/Trait/LimitTrait.php
  tests/DataSet/PHP80/AttributeDataSet80Test.php
  tests/DataSet/PHP81/AttributeDataSet81Test.php
  tests/Rule/CountHandlerTest.php
  tests/Rule/CountTest.php
  tests/Rule/HasLengthHandlerTest.php
  tests/Rule/HasLengthTest.php
Labels: type:enhancement, status:code review

#277 Test "enableIdn" option with no intl extension available (Email, Url rules), CI approach
  .github/workflows/build.yml
  phpunit.xml.dist
  tests/Rule/EmailHandlerTest.php
  tests/Rule/EmailTest.php
  tests/Rule/UrlHandlerTest.php
  tests/Rule/UrlTest.php
  tests/bootstrap.php
Labels: type:test
