Repository yiisoft/validator, pull requests merged in 2022-08, with the labels that each got.

#278 Remove ArrayShape attributes from getOptions()
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Callback.php
  src/Rule/Compare.php
  src/Rule/Count.php
  src/Rule/Email.php
  src/Rule/HasLength.php
  src/Rule/InRange.php
  src/Rule/Json.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/Subset.php
  src/Rule/Url.php
Labels: type:task

#285 Do not throw MissingAttributeException
  src/DataSet/ArrayDataTrait.php
  src/DataSet/ScalarDataSet.php
  src/DataSetInterface.php
  src/Exception/MissingAttributeException.php
  tests/Stub/DataSet.php
  tests/Stub/RulesProvidedDataSet.php
  tests/ValidatorTest.php
Labels: type:bug

#270 Ability validate objects with attributes directly
  README.md
  src/DataSet/AttributeDataSet.php
  src/Validator.php
Labels: status:code review

#279 Add shortcut for Nested + Each
  README.md
  composer.json
  src/Error.php
  src/Result.php
  src/Rule/EachHandler.php
  src/Rule/Nested.php
  src/Rule/NestedHandler.php
  tests/ResultTest.php
  tests/Rule/EachHandlerTest.php
  tests/Rule/NestedHandlerTest.php
  tests/Rule/NestedTest.php
Labels: type:enhancement, status:code review

#291 Improve validation logic
  .github/workflows/build.yml
  README.md
  src/DataSet/ArrayDataSet.php
  src/DataSet/ArrayDataTrait.php
  src/DataSet/AttributeDataSet.php
  src/DataSet/MixedDataSet.php
  src/DataSet/ObjectDataSet.php
  src/Validator.php
  tests/DataSet/ArrayDataSetTest.php
  tests/DataSet/MixedDataSetTest.php
  tests/DataSet/ObjectDataSetTest.php
  tests/DataSet/PHP80/ObjectDataSet80Test.php
  tests/DataSet/PHP81/ObjectDataSet81Test.php
  tests/Stub/ObjectWithAttributesOnly.php
  tests/Stub/ObjectWithDataSet.php
  tests/Stub/ObjectWithDataSetAndRulesProvider.php
  tests/Stub/ObjectWithDifferentPropertyVisibility.php
  tests/Stub/ObjectWithRulesProvider.php
  tests/ValidateLogicTest.php
  tests/ValidatorTest.php
Labels: status:code review

#290 Improve formatting of true and false values in Boolean and IsTrue rules
  src/Rule/Boolean.php
  src/Rule/BooleanHandler.php
  src/Rule/IsTrue.php
  src/Rule/IsTrueHandler.php
  tests/Rule/BooleanHandlerTest.php
  tests/Rule/BooleanTest.php
  tests/Rule/IsTrueHandlerTest.php
  tests/Rule/IsTrueTest.php
Labels: type:task

#288 Adjust skip on empty
  README.md
  src/Attribute/Embedded.php
  src/BeforeValidationInterface.php
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Callback.php
  src/Rule/Compare.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/Equal.php
  src/Rule/GreaterThan.php
  src/Rule/GreaterThanOrEqual.php
  src/Rule/HasLength.php
  src/Rule/InRange.php
  src/Rule/InRangeHandler.php
  src/Rule/Ip.php
  src/Rule/IsTrue.php
  src/Rule/Json.php
  src/Rule/LessThan.php
  src/Rule/LessThanOrEqual.php
  src/Rule/Nested.php
  src/Rule/NotEqual.php
  src/Rule/Number.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/Subset.php
  src/Rule/Trait/BeforeValidationTrait.php
  src/Rule/Trait/PreValidateTrait.php
  src/Rule/Url.php
  src/SkipOnEmptyCallback/SkipNone.php
  src/SkipOnEmptyCallback/SkipOnEmpty.php
  src/SkipOnEmptyCallback/SkipOnNull.php
  src/Validator.php
  tests/Rule/AbstractRuleTest.php
  tests/Rule/IpTest.php
  tests/ValidatorTest.php
Labels: type:enhancement

#297 Improve and merge `Embedded` and `Nested`
  .editorconfig
  README.md
  phpunit.xml.dist
  src/Attribute/Embedded.php
  src/Rule/Nested.php
  src/Rule/NestedHandler.php
  src/RulesProvider/AttributesRulesProvider.php
  src/Validator.php
  tests/Data/Charts/Chart.php
  tests/Data/Charts/Point.php
  tests/DataSet/PHP81/ObjectDataSet81Test.php
  tests/Php81/Rule/NestedTest.php
  tests/Rule/NestedHandlerTest.php
  tests/Rule/NestedTest.php
  tests/RulesProvider/AttributesRulesProviderTest.php
  tests/Stub/InheritAttributesObject/InheritAttributesObject.php
  tests/Stub/InheritAttributesObject/ParentInheritAttributesObject.php
  tests/Stub/ObjectWithNestedObject.php
  tests/Stub/SimpleRulesProvider.php
Labels: status:code review

#298 Allow empty rules in `Nested` rule
  src/Rule/Nested.php
  tests/Rule/NestedTest.php
Labels: status:code review

#299 Fix errors path when `Nested` used into `Each`
  src/Rule/EachHandler.php
  tests/Rule/NestedTest.php
  tests/Stub/EachNestedObjects/Bar.php
  tests/Stub/EachNestedObjects/Foo.php
Labels: status:code review

#300 Merge `skipOnEmpty` and `skipOnEmptyCallback`
  src/BeforeValidationInterface.php
  src/Rule/AtLeast.php
  src/Rule/Boolean.php
  src/Rule/Callback.php
  src/Rule/Compare.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/Equal.php
  src/Rule/GreaterThan.php
  src/Rule/GreaterThanOrEqual.php
  src/Rule/HasLength.php
  src/Rule/InRange.php
  src/Rule/Ip.php
  src/Rule/IsTrue.php
  src/Rule/Json.php
  src/Rule/LessThan.php
  src/Rule/LessThanOrEqual.php
  src/Rule/Nested.php
  src/Rule/NotEqual.php
  src/Rule/Number.php
  src/Rule/Regex.php
  src/Rule/Required.php
  src/Rule/Subset.php
  src/Rule/Trait/BeforeValidationTrait.php
  src/Rule/Trait/PreValidateTrait.php
  src/Rule/Trait/SkipOnEmptyTrait.php
  src/Rule/Url.php
  src/SkipOnEmptyInterface.php
  src/SkipOnEmptyNormalizer.php
  src/Validator.php
  tests/Rule/AbstractRuleTest.php
  tests/Rule/NestedTest.php
  tests/Stub/NotNullRule/NotNull.php
  tests/Stub/NotNullRule/NotNullHandler.php
  tests/ValidatorTest.php
Labels: status:code review
