Repository yiisoft/validator, pull requests merged in 2023-01, with the labels that each got.

#501 Fix error in phpdoc of `WhenInterface`
  src/WhenInterface.php
Labels: status:code review

#499 Improve description of `WhenNull` + more tests
  src/EmptyCriteria/WhenNull.php
  tests/EmptyCriteria/WhenNullTest.php
Labels: status:code review

#498 Change order of `Count` constructor parameters
  src/Rule/Count.php
  tests/Rule/Base/RuleTestCase.php
  tests/Rule/CountTest.php
Labels: status:code review

#500 Add `WhenMissing` empty criteria
  src/EmptyCriteria/WhenMissing.php
  tests/EmptyCriteria/WhenMissingTest.php
Labels: status:code review

#506 Docs, part 17
  src/Helper/RulesNormalizer.php
  src/Helper/RulesNormalizerIterator.php
  tests/Rule/CompositeTest.php
  tests/ValidatorTest.php
Labels: type:docs, type:task

#505 Docs, part 16
  src/DataSet/ObjectDataSet.php
  src/Helper/ObjectParser.php
  src/Helper/RulesNormalizer.php
  src/Helper/RulesNormalizerIterator.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/Rule/NestedHandler.php
  src/ValidationContext.php
  src/Validator.php
  tests/Rule/CompositeTest.php
  tests/Rule/NestedTest.php
  tests/TestEnvironments/Php81/Rule/NestedTest.php
  tests/ValidatorTest.php
Labels: type:docs, type:task

#507 Docs, part 18
  README.md
  docs/guide/README.md
  docs/guide/built-in-rules-callback.md
  docs/guide/built-in-rules-composite.md
  docs/guide/built-in-rules-each.md
  docs/guide/built-in-rules-nested.md
  docs/guide/built-in-rules-required.md
  docs/guide/built-in-rules-stop-on-error.md
  docs/guide/built-in-rules.md
  docs/guide/client-side-validation.md
  docs/guide/conditional-validation.md
  docs/guide/configuring-rules-via-php-attributes.md
  docs/guide/creating-custom-rules.md
  docs/guide/customizing-error-messages.md
  docs/guide/extensions.md
  docs/guide/result.md
  docs/guide/using-validator.md
  docs/images/chart.png
  src/DataSet/ObjectDataSet.php
  src/Helper/ObjectParser.php
  src/Rule/AtLeast.php
  src/RulesProvider/AttributesRulesProvider.php
  tests/Helper/ObjectParserTest.php
  tests/Rule/CompositeTest.php
  tests/Support/Data/InheritAttributesObject/InheritAttributesObject.php
  tests/Support/Data/InheritAttributesObject/ParentInheritAttributesObject.php
  tests/Support/Rule/CoordinatesRuleSet.php
  tests/Support/Rule/CustomUrlRuleSet.php
Labels: type:docs

#517 Rename "criteria" to "condition"
  docs/guide/built-in-rules-each.md
  docs/guide/built-in-rules-required.md
  docs/guide/conditional-validation.md
  src/EmptyCondition/NeverEmpty.php
  src/EmptyCondition/WhenEmpty.php
  src/EmptyCondition/WhenMissing.php
  src/EmptyCondition/WhenNull.php
  src/Helper/RulesNormalizer.php
  src/Helper/RulesNormalizerIterator.php
  src/Helper/SkipOnEmptyNormalizer.php
  src/Rule/AtLeastHandler.php
  src/Rule/Required.php
  src/Rule/RequiredHandler.php
  src/SkipOnEmptyInterface.php
  src/Validator.php
  tests/EmptyCondition/WhenMissingTest.php
  tests/EmptyCondition/WhenNullTest.php
  tests/Helper/SkipOnEmptyNormalizerTest.php
  tests/Rule/AtLeastTest.php
  tests/Rule/RequiredTest.php
  tests/ValidatorTest.php
Labels: type:task
