Repository yiisoft/validator, pull requests merged in 2023-02, with the labels that each got.

#519 Rename remaining rules, fix links in guide for built-in rules
  docs/guide/built-in-rules-composite.md
  docs/guide/built-in-rules-nested.md
  docs/guide/built-in-rules-required.md
  docs/guide/built-in-rules-stop-on-error.md
  docs/guide/built-in-rules.md
  docs/guide/client-side-validation.md
  docs/guide/conditional-validation.md
  docs/guide/configuring-rules-via-php-attributes.md
  docs/guide/creating-custom-rules.md
  docs/guide/customizing-error-messages.md
  docs/guide/extensions.md
  docs/guide/using-validator.md
  src/DataSet/ObjectDataSet.php
  src/Helper/ObjectParser.php
  src/Helper/RulesDumper.php
  src/Rule/AbstractCompare.php
  src/Rule/Compare.php
  src/Rule/CompareHandler.php
  src/Rule/CompareTo.php
  src/Rule/CompareType.php
  src/Rule/Composite.php
  src/Rule/Equal.php
  src/Rule/GreaterThan.php
  src/Rule/GreaterThanOrEqual.php
  src/Rule/Length.php
  src/Rule/LengthHandler.php
  src/Rule/LessThan.php
  src/Rule/LessThanOrEqual.php
  src/Rule/Nested.php
  src/Rule/NotEqual.php
  src/Rule/StopOnError.php
  src/RulesProvider/AttributesRulesProvider.php
  tests/DataSet/DataSetUsageTest.php
  tests/DataSet/ObjectDataSetTest.php
  tests/Rule/AbstractCompareTest.php
  tests/Rule/CompareTest.php
  tests/Rule/CompareToTest.php
  tests/Rule/EqualTest.php
  tests/Rule/GreaterThanOrEqualTest.php
  tests/Rule/GreaterThanTest.php
  tests/Rule/LengthTest.php
  tests/Rule/LessThanOrEqualTest.php
  tests/Rule/LessThanTest.php
  tests/Rule/NestedTest.php
  tests/Rule/NotEqualTest.php
  tests/Rule/StopOnErrorTest.php
  tests/RulesProvider/AttributesRulesProviderTest.php
  tests/Support/Data/IteratorWithBooleanKey.php
  tests/Support/Data/ObjectWithAttributesOnly.php
  tests/Support/Data/ObjectWithNestedObject.php
  tests/Support/Data/SimpleForm.php
  tests/Support/Data/TitleTrait.php
  tests/Support/Rule/CustomUrlRuleSet.php
  tests/TestEnvironments/Php81/DataSet/ObjectDataSetTest.php
  tests/ValidatorTest.php
Labels: type:task

#527 Change guide structure
  README.md
  docs/guide/built-in-rules.md
  docs/guide/en/README.md
  docs/guide/en/built-in-rules-callback.md
  docs/guide/en/built-in-rules-composite.md
  docs/guide/en/built-in-rules-each.md
  docs/guide/en/built-in-rules-nested.md
  docs/guide/en/built-in-rules-required.md
  docs/guide/en/built-in-rules-stop-on-error.md
  docs/guide/en/built-in-rules.md
  docs/guide/en/client-side-validation.md
  docs/guide/en/conditional-validation.md
  docs/guide/en/configuring-rules-via-php-attributes.md
  docs/guide/en/creating-custom-rules.md
  docs/guide/en/customizing-error-messages.md
  docs/guide/en/extensions.md
  docs/guide/en/result.md
  docs/guide/en/using-validator.md
  docs/guide/images/chart.png
Labels: type:task

#538 Adjust naming for countable limits
  src/CountableLimitInterface.php
  src/Rule/Count.php
  src/Rule/CountHandler.php
  src/Rule/Length.php
  src/Rule/LengthHandler.php
  src/Rule/Trait/CountableLimitHandlerTrait.php
  src/Rule/Trait/CountableLimitTrait.php
  tests/Rule/CountableLimitHandlerTraitTest.php
Labels: type:task

#539 Group similar messages, categorize translations
  docs/guide/en/built-in-rules-callback.md
  docs/guide/en/client-side-validation.md
  messages/pl/yii-validator.php
  messages/ru/yii-validator.php
  messages/uz/yii-validator.php
  src/Error.php
  src/Helper/RulesDumper.php
  src/Rule/AtLeast.php
  src/Rule/Email.php
  src/Rule/Ip.php
  src/Rule/Json.php
  src/Rule/Length.php
  src/Rule/Nested.php
  src/Rule/Regex.php
  src/Rule/Url.php
  tests/Rule/AtLeastTest.php
  tests/Rule/EmailTest.php
  tests/Rule/IpTest.php
  tests/Rule/JsonTest.php
  tests/Rule/LengthTest.php
  tests/Rule/NestedTest.php
  tests/Rule/RegexTest.php
  tests/Rule/StopOnErrorTest.php
  tests/Rule/UrlTest.php
Labels: type:task

#541 Fix unit tests
  tests/Rule/EmailTest.php
Labels: type:bug

#540 Reorder arguments in Length rule
  src/Rule/Length.php
  tests/Rule/LengthTest.php
Labels: type:task

#543 Fix unit tests for newer version of PHPUnit
  tests/Helper/ObjectParserTest.php
  tests/ValidationContextTest.php
Labels: type:bug, type:test

#542 Cleanup shortcut rules
  src/Rule/AbstractCompare.php
  src/Rule/AbstractNumber.php
  src/Rule/Equal.php
  src/Rule/GreaterThan.php
  src/Rule/GreaterThanOrEqual.php
  src/Rule/Integer.php
  src/Rule/LessThan.php
  src/Rule/LessThanOrEqual.php
  src/Rule/NotEqual.php
  tests/Rule/CompareTest.php
  tests/Rule/EqualTest.php
  tests/Rule/GreaterThanOrEqualTest.php
  tests/Rule/GreaterThanTest.php
  tests/Rule/LessThanOrEqualTest.php
  tests/Rule/LessThanTest.php
  tests/Rule/NotEqualTest.php
  tests/ValidatorTest.php
Labels: type:bug, type:task

#548 Allow use `PostValidationHookInterface` for any object
  psalm.xml
  src/PostValidationHookInterface.php
  src/Validator.php
  tests/Support/Data/DataSetWithPostValidationHook.php
  tests/Support/Data/ObjectWithPostValidationHook.php
  tests/ValidatorTest.php
Labels: status:code review

#552 Adapt configuration group names to Yii conventions
  composer.json
  config/di.php
  tests/BaseConfigTest.php
Labels: status:code review

#521 Fix float numbers equality and type casting in `Compare` rule, add datetime support, various improvements
  docs/guide/en/built-in-rules-compare.md
  docs/guide/en/built-in-rules.md
  messages/pl/yii-validator.php
  messages/ru/yii-validator.php
  messages/uz/yii-validator.php
  src/Rule/AbstractCompare.php
  src/Rule/Compare.php
  src/Rule/CompareHandler.php
  src/Rule/CompareType.php
  src/Rule/Equal.php
  src/Rule/GreaterThan.php
  src/Rule/GreaterThanOrEqual.php
  src/Rule/LessThan.php
  src/Rule/LessThanOrEqual.php
  src/Rule/NotEqual.php
  tests/Rule/CompareTest.php
  tests/Rule/EqualTest.php
  tests/Rule/GreaterThanOrEqualTest.php
  tests/Rule/GreaterThanTest.php
  tests/Rule/LessThanOrEqualTest.php
  tests/Rule/LessThanTest.php
  tests/Rule/NotEqualTest.php
  tests/Support/Data/CompareObject.php
Labels: type:bug

#560 Add PHPDoc for isolated data set
  src/ValidationContext.php
Labels: type:docs

#557 Consider missing attribute in context validation
  src/ValidationContext.php
  tests/Rule/StopOnErrorTest.php
Labels: type:bug, status:code review

#555 Add `StopOnError::$skipOnError`
  docs/guide/en/built-in-rules-stop-on-error.md
  src/Rule/StopOnError.php
  src/Rule/StopOnErrorHandler.php
  tests/Rule/StopOnErrorTest.php
Labels: type:enhancement

#559 Add isolated data set to validation context
  src/ValidationContext.php
  src/Validator.php
  tests/Rule/NestedTest.php
  tests/ValidationContextTest.php
Labels: status:code review

#564 Allow any deep level in `Nested` rule
  docs/guide/en/built-in-rules-nested.md
  messages/pl/yii-validator.php
  messages/ru/yii-validator.php
  messages/uz/yii-validator.php
  src/Helper/PropagateOptionsHelper.php
  src/Rule/Nested.php
  src/Rule/NestedHandler.php
  tests/Rule/NestedTest.php
Labels: status:code review

#550 Use `RulesProviderInterface` in complex rules (`Nested`, `Each`, `Composite`, `StopOnError`)
  docs/guide/en/built-in-rules-composite.md
  src/DataSet/ObjectDataSet.php
  src/Helper/RulesNormalizer.php
  src/Rule/Composite.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/Rule/StopOnError.php
  src/RulesProvider/AttributesRulesProvider.php
  src/RulesProviderInterface.php
  src/ValidationContext.php
  src/Validator.php
  src/ValidatorInterface.php
  tests/Rule/Base/RuleWithProvidedRulesTrait.php
  tests/Rule/CompositeTest.php
  tests/Rule/EachTest.php
  tests/Rule/NestedTest.php
  tests/Rule/StopOnErrorTest.php
  tests/Support/Rule/CoordinatesRuleSet.php
Labels: type:task

#572 Correction to PR #571
  tests/Rule/EachTest.php
  tests/Rule/StopOnErrorTest.php
Labels: type:task

#571 Remove `RulesProviderInterface` from rules
  src/Rule/Composite.php
  src/Rule/Each.php
  src/Rule/StopOnError.php
  tests/Rule/Base/RuleWithProvidedRulesTrait.php
  tests/Rule/EachTest.php
  tests/Rule/NestedTest.php
  tests/Rule/StopOnErrorTest.php
Labels: status:code review

#566 Use validator rules format in Each
  src/DataSet/ObjectDataSet.php
  src/Helper/PropagateOptionsHelper.php
  src/Helper/RulesNormalizer.php
  src/Rule/Composite.php
  src/Rule/Each.php
  src/Rule/EachHandler.php
  src/Rule/StopOnError.php
  src/RulesProvider/AttributesRulesProvider.php
  src/RulesProviderInterface.php
  src/ValidationContext.php
  src/Validator.php
  src/ValidatorInterface.php
  tests/Rule/EachTest.php
  tests/Rule/NestedTest.php
  tests/TestEnvironments/Php81/DataSet/ObjectDataSetTest.php
  tests/TestEnvironments/Support/Data/Charts/Point.php
Labels: type:enhancement, status:code review

#575 Fix #573
  src/Helper/PropagateOptionsHelper.php
  src/Rule/Nested.php
  tests/Rule/NestedTest.php
Labels: type:task

#573 Fix mutant in `Nested::propagateOptions()`, add and simplify tests
  src/Rule/Each.php
  tests/Rule/NestedTest.php
  tests/Support/Helper/OptionsHelper.php
Labels: type:task

#574 Improve readme + Update bc.yml and code of conduct
  .github/CODE_OF_CONDUCT.md
  .github/workflows/bc.yml_
  README.md
  docs/internals.md
Labels: status:code review

#576 Fix new mutants
  src/AfterInitAttributeEventInterface.php
  src/Rule/AbstractNumber.php
  src/Rule/Callback.php
  src/Rule/Composite.php
  src/Rule/Each.php
  src/Rule/Nested.php
  src/Rule/StopOnError.php
  tests/Rule/CallbackTest.php
  tests/Rule/CompareTest.php
  tests/ValidatorTest.php
Labels: type:task

#578 `Compare` - fix mutant and bug with using `>=` and `<=` operators with floats
  src/Rule/CompareHandler.php
  tests/Rule/CompareTest.php
Labels: type:bug

#577 Actualize features list in README
  README.md
Labels: type:docs

#579 Temporarily decrease min covered MSI, fix badge for mutation tests
  .github/workflows/mutation.yml
  README.md
Labels: type:task

#584 Clarify README about PHP 8 attributes support
  README.md
Labels: type:docs

#585 Remove JSON extension requirement from README
  README.md
Labels: type:docs

#580 Fix remaining mutants
  .github/workflows/mutation.yml
  src/Helper/ObjectParser.php
  src/Rule/CompareHandler.php
  tests/Helper/ObjectParserTest.php
  tests/Support/Data/ObjectForTestingCache1.php
  tests/Support/Data/ObjectForTestingCache2.php
  tests/Support/Data/ObjectForTestingDisabledCache.php
Labels: type:test

#587 Fix missing dots at the end of sentence for error translations
  messages/pl/yii-validator.php
  messages/uz/yii-validator.php
Labels: type:task

#588 Add PHPDoc for `ValidationContext::PARAMETER_VALUE_AS_ARRAY`
  src/ValidationContext.php
Labels: type:docs
