Repository yiisoft/validator, pull requests merged in 2024-04, with the labels that each got.

#680 Add missed params to `Image` rule options
  CHANGELOG.md
  src/Rule/Image/Image.php
  tests/Rule/Image/ImageTest.php
Labels: status:code review

#681 Add aspect ratio support to `Image` rule
  CHANGELOG.md
  src/Rule/Image/Image.php
  src/Rule/Image/ImageAspectRatio.php
  src/Rule/Image/ImageHandler.php
  src/RuleHandlerResolver/SimpleRuleHandlerContainer.php
  tests/Rule/Image/ImageTest.php
Labels: type:feature

#686 Add `Result::add()` method for merging other results to the base one
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  src/Result.php
  tests/ResultTest.php
Labels: type:feature

#696 Change signature of `RuleHandlerInteface::validate()`
  CHANGELOG.md
  UPGRADE.md
  docs/guide/en/creating-custom-rules.md
  src/Exception/UnexpectedRuleException.php
  src/Rule/AtLeastHandler.php
  src/Rule/BooleanValueHandler.php
  src/Rule/CallbackHandler.php
  src/Rule/CompareHandler.php
  src/Rule/CompositeHandler.php
  src/Rule/CountHandler.php
  src/Rule/Date/BaseDateHandler.php
  src/Rule/DateTimeHandler.php
  src/Rule/EachHandler.php
  src/Rule/EmailHandler.php
  src/Rule/Image/ImageHandler.php
  src/Rule/InHandler.php
  src/Rule/IpHandler.php
  src/Rule/JsonHandler.php
  src/Rule/LengthHandler.php
  src/Rule/NestedHandler.php
  src/Rule/NumberHandler.php
  src/Rule/OneOfHandler.php
  src/Rule/RegexHandler.php
  src/Rule/RequiredHandler.php
  src/Rule/StopOnErrorHandler.php
  src/Rule/StringValueHandler.php
  src/Rule/SubsetHandler.php
  src/Rule/TrueValueHandler.php
  src/Rule/UrlHandler.php
  src/RuleHandlerInterface.php
  tests/Rule/CountableLimitHandlerTraitTest.php
  tests/Rule/RuleWithBuiltInHandler.php
  tests/RuleHandlerResolver/SimpleRuleHandlerContainerTest.php
  tests/Support/Rule/NotNullRule/NotNullHandler.php
  tests/Support/Rule/PiHandler.php
  tests/Support/Rule/StubRule/StubRuleHandler.php
Labels: status:code review, type:task

#701 Rename AnyHandler (remaining occurence)
  src/Rule/AnyRule.php
Labels: type:bug

#697 Add methods for getting first error messages to `Result`
  CHANGELOG.md
  src/Result.php
  tests/ResultTest.php
Labels: status:code review, type:feature

#702 Change type of `$escape` argument in `Error::getValuePath()` from `bool|string|null` to `string|null`
  CHANGELOG.md
  UPGRADE.md
  src/Error.php
  tests/ErrorTest.php
Labels: status:code review, type:task

#695 Add `Unique` rule
  CHANGELOG.md
  docs/guide/en/built-in-rules.md
  messages/ru/yii-validator.php
  src/Rule/UniqueIterable.php
  src/Rule/UniqueIterableHandler.php
  tests/Rule/UniqueIterableTest.php
Labels: status:code review, type:feature

#705 Fix typo in array shape
  src/Rule/UniqueIterable.php
Labels: type:bug

#698 Change type of `$skipOnEmpty` argument in rules' constructors from `mixed` to `bool|callable|null`
  CHANGELOG.md
  UPGRADE.md
  src/Rule/AbstractCompare.php
  src/Rule/AbstractNumber.php
  src/Rule/AtLeast.php
  src/Rule/BooleanValue.php
  src/Rule/Callback.php
  src/Rule/Composite.php
  src/Rule/Count.php
  src/Rule/Date/BaseDate.php
  src/Rule/Date/Date.php
  src/Rule/Date/DateTime.php
  src/Rule/Date/Time.php
  src/Rule/DateTime.php
  src/Rule/Each.php
  src/Rule/Email.php
  src/Rule/Image/Image.php
  src/Rule/In.php
  src/Rule/Integer.php
  src/Rule/Ip.php
  src/Rule/Json.php
  src/Rule/Length.php
  src/Rule/Nested.php
  src/Rule/Number.php
  src/Rule/OneOf.php
  src/Rule/Regex.php
  src/Rule/StopOnError.php
  src/Rule/StringValue.php
  src/Rule/Subset.php
  src/Rule/Trait/SkipOnEmptyTrait.php
  src/Rule/TrueValue.php
  src/Rule/Url.php
  tests/Helper/SkipOnEmptyNormalizerTest.php
  tests/Rule/CompositeTest.php
Labels: status:code review, type:task
