Repository yiisoft/validator, pull requests merged in 2024-07, with the labels that each got.

#726 Code style
  CHANGELOG.md
  src/Result.php
Labels: status:code review

#729 Fix PHPDoc and add type in tests
  src/Rule/Nested.php
  tests/TestEnvironments/Support/Data/Charts/Point.php
Labels: type:docs, type:test

#733 Fix don't usage PHP attributes in `RulesNormalizer::normalize()` + make `$rules` optional
  CHANGELOG.md
  src/Helper/RulesNormalizer.php
  tests/Helper/RulesNormalizerTest.php
Labels: status:code review

#732 Rename `Coordinate` class in tests
  tests/TestEnvironments/Support/Data/Charts/Coordinates.php
  tests/TestEnvironments/Support/Data/Charts/Point.php
Labels: type:test

#718 Sync attribute translations
  CHANGELOG.md
  messages/ru/yii-validator.php
  src/Rule/AbstractCompare.php
  src/Rule/AbstractNumber.php
  src/Rule/AtLeast.php
  src/Rule/AtLeastHandler.php
  src/Rule/BooleanValue.php
  src/Rule/CompareHandler.php
  src/Rule/Date/DateHandler.php
  src/Rule/Date/DateTimeHandler.php
  src/Rule/Date/TimeHandler.php
  src/Rule/Each.php
  src/Rule/Image/Image.php
  src/Rule/Nested.php
  src/Rule/NestedHandler.php
  src/Rule/Number.php
  src/Rule/OneOf.php
  src/Rule/OneOfHandler.php
  src/Rule/TrueValue.php
  src/Rule/Type/BooleanType.php
  src/Rule/Type/FloatType.php
  src/Rule/Type/IntegerType.php
  src/Rule/Type/StringType.php
  src/Rule/UniqueIterable.php
  tests/EmptyCondition/WhenMissingTest.php
  tests/Helper/RulesDumperTest.php
  tests/Rule/AnyRuleTest.php
  tests/Rule/AtLeastTest.php
  tests/Rule/BooleanValueTest.php
  tests/Rule/CompareTest.php
  tests/Rule/CompositeTest.php
  tests/Rule/Date/DateTest.php
  tests/Rule/Date/DateTimeTest.php
  tests/Rule/Date/TimeTest.php
  tests/Rule/EachTest.php
  tests/Rule/EqualTest.php
  tests/Rule/GreaterThanOrEqualTest.php
  tests/Rule/GreaterThanTest.php
  tests/Rule/Image/ImageTest.php
  tests/Rule/LessThanOrEqualTest.php
  tests/Rule/LessThanTest.php
  tests/Rule/NestedTest.php
  tests/Rule/NotEqualTest.php
  tests/Rule/NumberTest.php
  tests/Rule/OneOfTest.php
  tests/Rule/TrueValueTest.php
  tests/Rule/Type/BooleanTypeTest.php
  tests/Rule/Type/FloatTypeTest.php
  tests/Rule/Type/IntegerTypeTest.php
  tests/Rule/Type/StringTypeTest.php
  tests/Rule/UniqueIterableTest.php
  tests/ValidatorTest.php
Labels: type:task

#734 Add enum support
  CHANGELOG.md
  docs/guide/en/built-in-rules.md
  src/Rule/InEnum.php
  src/Rule/InEnumHandler.php
  tests/Rule/InEnumTest.php
  tests/Support/Data/Enum/BackedEnumStatus.php
  tests/Support/Data/Enum/EnumStatus.php
  tests/Support/Data/Enum/IntBackedEnumStatus.php
Labels: type:enhancement

#736 Add type to error messages related with incorrect input
  CHANGELOG.md
  messages/ru/yii-validator.php
  src/Rule/AbstractCompare.php
  src/Rule/AbstractNumber.php
  src/Rule/AtLeast.php
  src/Rule/Count.php
  src/Rule/Each.php
  src/Rule/EachHandler.php
  src/Rule/Email.php
  src/Rule/InEnumHandler.php
  src/Rule/Ip.php
  src/Rule/Json.php
  src/Rule/Length.php
  src/Rule/Nested.php
  src/Rule/Number.php
  src/Rule/OneOf.php
  src/Rule/Regex.php
  src/Rule/Subset.php
  src/Rule/Type/StringType.php
  src/Rule/Url.php
  tests/EmptyCondition/WhenMissingTest.php
  tests/Helper/RulesDumperTest.php
  tests/Rule/AtLeastTest.php
  tests/Rule/CompareTest.php
  tests/Rule/CompositeTest.php
  tests/Rule/CountTest.php
  tests/Rule/EachTest.php
  tests/Rule/EmailTest.php
  tests/Rule/EqualTest.php
  tests/Rule/GreaterThanOrEqualTest.php
  tests/Rule/GreaterThanTest.php
  tests/Rule/IpTest.php
  tests/Rule/JsonTest.php
  tests/Rule/LengthTest.php
  tests/Rule/LessThanOrEqualTest.php
  tests/Rule/LessThanTest.php
  tests/Rule/NestedTest.php
  tests/Rule/NotEqualTest.php
  tests/Rule/NumberTest.php
  tests/Rule/OneOfTest.php
  tests/Rule/RegexTest.php
  tests/Rule/StopOnErrorTest.php
  tests/Rule/SubsetTest.php
  tests/Rule/Type/StringTypeTest.php
  tests/Rule/UrlTest.php
  tests/ValidatorTest.php
Labels: status:code review, type:task
