Repository yiisoft/validator, pull requests merged in 2024-03, with the labels that each got.

#668 Clarify psalm types in `Result`
  CHANGELOG.md
  composer-require-checker.json
  src/Result.php
Labels: status:code review

#671 Image validator additions
  docs/guide/en/built-in-rules.md
  src/Rule/Image.php
  src/Rule/ImageHandler.php
  tests/Rule/Image/ImageTest.php
Labels: type:docs

#670 Add `Image` validation rule
  .github/workflows/build.yml
  CHANGELOG.md
  composer-require-checker.json
  composer.json
  docs/guide/en/built-in-rules.md
  src/Rule/Image/CompositeImageInfoProvider.php
  src/Rule/Image/Image.php
  src/Rule/Image/ImageHandler.php
  src/Rule/Image/ImageInfo.php
  src/Rule/Image/ImageInfoProviderInterface.php
  src/Rule/Image/NativeImageInfoProvider.php
  tests/Rule/Base/RuleTestCase.php
  tests/Rule/CompareTest.php
  tests/Rule/Image/16x18.jpg
  tests/Rule/Image/16x18.png
  tests/Rule/Image/797x808.HEIC
  tests/Rule/Image/CompositeImageInfoProviderTest.php
  tests/Rule/Image/ImageTest.php
  tests/Rule/Image/StubImageInfoProvider.php
Labels: status:code review, type:feature
